name: Deploy Infrastructure

on: workflow_dispatch

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    outputs:
      exit_code: ${{ steps.terraform_plan.outputs.exit_code }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan
        run: |
          terraform plan -input=false -detailed-exitcode
          echo "exit_code=$?" | tee -a $GITHUB_OUTPUT

  terraform-apply:
    name: Terraform Apply
    needs:
      - terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.exit_code == 2
    environment: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

  colmena-build:
    name: Colmena Build
    needs:
      - terraform-apply
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
      - name: Install dependencies
        run: nix develop --command echo "dependencies installed"
      - name: colmena build
        run: nix develop --command colmena "build"

  colmena-apply:
    name: Colmena Apply
    needs:
      - colmena-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          path: infrastructure

      - uses: actions/checkout@v4
        with:
          repository: nevarro-space/infrastructure-secrets
          token: ${{ secrets.SECRET_REPO_CLONE_TOKEN }}
          path: infrastructure-secrets

      - uses: nixbuild/nix-quick-install-action@v28

      - name: Install dependencies
        run: |
          cd infrastructure
          nix develop --command echo "dependencies installed"

      - name: colmena apply
        run: |
          cd infrastructure
          nix develop --command colmena "apply"
